<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Language strings for local_sqlchat.
 *
 * @package    local_sqlchat
 * @copyright  2026 Marcus Green
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'SQL Chat';

$string['sqlchat:use'] = 'Use SQL Chat to generate and run SQL queries via LLM';

$string['settings:maxrows'] = 'Maximum result rows';
$string['settings:maxrows_desc'] = 'Hard cap on rows returned per query.';
$string['settings:timeoutsec'] = 'Query timeout (seconds)';
$string['settings:timeoutsec_desc'] = 'Statement timeout enforced on the read-only connection.';
$string['settings:purpose'] = 'AI bridge purpose';
$string['settings:purpose_desc'] = 'Routing tag passed to tool_ai_bridge::perform_request().';

$string['cachedef_schema'] = 'Compressed Moodle schema cache';

$string['form:question'] = 'Question';
$string['form:question_help'] = 'Plain English description of the data you want.';
$string['form:submit'] = 'Generate SQL';
$string['form:execute'] = 'Run SQL';

$string['result:sql'] = 'Generated SQL';
$string['result:rows'] = 'Rows returned: {$a}';
$string['result:tokens'] = 'Tokens used: {$a}';
$string['result:latency'] = 'Latency: {$a} ms';

$string['error:onlyselect'] = 'Only SELECT statements are permitted.';
$string['error:blockedkeyword'] = 'Blocked SQL keyword: {$a}';
$string['error:nosemicolons'] = 'Stacked statements are not permitted.';
$string['error:llmempty'] = 'LLM returned no SQL.';
$string['error:execfailed'] = 'Query execution failed: {$a}';

$string['privacy:metadata'] = 'local_sqlchat logs the question, generated SQL, and execution metadata for each query made by a user.';
$string['privacy:metadata:log:userid'] = 'The user who made the query.';
$string['privacy:metadata:log:question'] = 'The natural-language question submitted.';
$string['privacy:metadata:log:sqlgenerated'] = 'The SQL generated by the LLM.';
$string['privacy:metadata:log:timecreated'] = 'When the query was made.';
